#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d • • • • •

bspc config border_width         2
bspc config window_gap           5
bspc config focused_border_color "#a6e3a1"

bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true
bspc config split_ratio          0.52
bspc config single_monacle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config borderless_floating  true

#bspc rule -a '*' border=off state=floating
bspc rule -a mpv state floating rectangle=1280x720+600+300
bspc rule -a feh state floating 
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a com.github.neithern.g4music state=floating rectangle=372x537+5+27 sticky=on
xsetroot -cursor_name left_ptr & 


#wallpaper
pkill feh
feh --bg-fill  ~/wallpapers/keqinglionsroar.png &

#compositor
pkill picom
picom -b &

#notifications
pkill dunst
dunst &

#statusbar
pkill polybar
polybar &

#input
ibus-daemon &
